export const NONE_OPTION = "None";

export const ALLERGY_OPTIONS = [
  "IgE-mediated food allergy",
  "Non-IgE-mediated food allergy",
  "Cow's milk protein allergy (CMPA)",
  "Egg allergy",
  "Peanut allergy",
  "Tree nut allergy",
  "Soy allergy",
  "Wheat allergy",
  "Fish allergy",
  "Shellfish allergy",
  "Sesame allergy",
  "Mustard allergy",
  "Corn allergy",
  "Rice allergy",
  "Fruit allergy",
  "Vegetable allergy",
  "Legume allergy",
  "Kiwi allergy",
  "Latex-fruit syndrome",
  "Lactose intolerance",
  "Fructose intolerance",
  "Hereditary fructose intolerance (HFI)",
  "Fructose malabsorption",
  "Sucrose intolerance",
  "Sucrase-isomaltase deficiency",
  "Galactose intolerance",
  "Glucose-galactose malabsorption",
  "Histamine intolerance",
  "Caffeine intolerance",
  "Alcohol intolerance",
  "Sulfite sensitivity/intolerance",
  "Salicylate intolerance",
  "MSG sensitivity/intolerance",
  "FODMAP intolerance",
  "Food additive/preservative sensitivity",
  "Nightshade sensitivity",
  "Chocolate/cocoa sensitivity",
  "Celiac disease",
  "Non-celiac gluten sensitivity (NCGS)",
  "Dermatitis herpetiformis",
  "Gluten ataxia",
  "Wheat-dependent exercise-induced anaphylaxis (WDEIA)",
  "Food protein-induced enterocolitis syndrome (FPIES)",
  "Food protein-induced allergic proctocolitis (FPIAP)",
  "Food protein-induced enteropathy (FPE)",
  "Oral allergy syndrome (OAS)",
  "Pollen-food allergy syndrome (PFAS)",
  "Food-dependent exercise-induced anaphylaxis (FDEIA)",
  "Alpha-gal syndrome",
] as const;